### ISSUE TITLE
building problem

### ISSUE THREAD

**Issue by caiotizio** [multigcs/cammill#11]
hello, i'd like to try your software, but i having trouble to compile under linux wheezy.
when i type "make" i get this error:

"xxxxxx@debian:~/Desktop/cammill$ make
mkdir -p intl/de_DE.UTF-8/LC_MESSAGES
msgfmt de.po -o intl/de_DE.UTF-8/LC_MESSAGES/cammill.mo
mkdir -p intl/it_IT.UTF-8/LC_MESSAGES
msgfmt it.po -o intl/it_IT.UTF-8/LC_MESSAGES/cammill.mo
clang -ggdb -Wall -Wno-unknown-pragmas -O3 -o cammill main.c pocket.c calc.c hersheyfont.c postprocessor.c setup.c dxf.c font.c texture.c -lGL -lglut -lGLU -lX11 -lm -lpthread -lstdc++ -lXext -ldl -lXi -lxcb -lXau -lXdmcp -lgcc -lc `pkg-config gtk+-2.0 --libs` `pkg-config gtk+-2.0 --cflags` `pkg-config gtkglext-x11-1.0 --libs` `pkg-config gtkglext-x11-1.0 --cflags` `pkg-config gtksourceview-2.0 --libs` `pkg-config gtksourceview-2.0 --cflags` `pkg-config lua5.1 --libs` `pkg-config lua5.1 --cflags` -I./ "-DGDK_DISABLE_DEPRECATED -DGTK_DISABLE_DEPRECATED" "-DGSEAL_ENABLE" "-DHERSHEY_FONTS_DIR=\"./\"" "-DUSE_POSTCAM"
/bin/sh: 1: clang: not found
make: *** [cammill] Error 127
"

all dependencies are installed.
i tried on fresh debian installation too, but result is the same.

**Comment by multigcs** [comment]
apt-get install clang

**Comment by caiotizio** [comment]
thank you.
i like this project and i'll glad to support it.
i made some fix on italian translation.
