### ISSUE TITLE
Pocket desn't always work

### ISSUE THREAD

**Issue by deusyss** [multigcs/cammill#12]
Hi,

Pocket function does'nt accept to work at each time we ask it. Some times, we check the checkbox, but pocket doesn't appears in 3D view and in NGC code.

**Comment by adbensi** [comment]
Please, try this https://github.com/adbensi/cammill I make changes, report if works for You.

**Comment by deusyss** [comment]
Hi, thanks for your quick answer. But it doesn't work.

I let you my file (rename.png to .dxf). It would be easier for you. The pocket should be the middle rectangle (Calque support ecrou). This dxf was made with LibreCad.

I ask myself if the problem is not the too small size of the rectangle. I thnik only one or two time, over the external cut of this rectangle, should be necessary.

**Comment by adbensi** [comment]
Please, go to cammil.org forum, I can not see Your file :/ I try it

**Comment by deusyss** [comment]
Hi,
Sorry from being (very) late to answer, personal problem.

After some search i finally find the problem, which could help someones. Pockets are available only for closely lines.

In my case, one side of a rectangle was deleted, but i didn't see it because another line, a longer one, was at the same place.

So if pocket doesn't appears, verify your closely lines.

Adbensi, thanks for your help.
