### ISSUE TITLE
Q: Future of the project

### ISSUE THREAD

**Issue by blacksheep1970** [multigcs/cammill#2]
Hi there,

I found no forum so I post my question here. I found a link to this project here by an accident in the linuxCNC forum and this software is awesome! While for example pyCAM is calculating for hours this piece of software returns the gcode instantely.

So I am now interested in the future of this project. Do you plan further releases / enhancements of cammill? I have a lot of feature requests :grin: 

If you need assistance (more for items like orga, forum and documentation since I am not a developer) let me know. I would like to push this awesome project as far as I can.

There should be more advertisement / announcements to get more users. From my perspective this is the first really useable open source CAM on Linux.

Regards,
Michael

**Comment by fordgt72** [comment]
Hi,
I also would like to know the future of this project. I agree with blacksheep1970, this is a great little piece of software. 

Like blacksheep1970 said there was no where I could find to post comments so i'm posting here. Please feel free to delete if need be.

So some issues. (maybe user related)
  1. Z safe won't go any lower than 1.0000. Can this be changed in source easily?
  2. Objects numbers in 3D view are too large in some files.(probably something I'm missing?)
  3. Large DXF files would cause cammill to load very slow or freeze. I believe due to Automatic Offsets. Could this be turned on/off?

Again cammill is a really nice program.
Thanks
Jeff

**Comment by onekk** [comment]
This is a great piece of software, how to write a preprocessor, or better, how to adjust the decimal points and set the G00 G01 move to the format  X Y Z F

Many thanks for the program and hope hear some new soons

Carlo

**Comment by multigcs** [comment]
the post is a lua-script, please take a look at the documenentation of sheetcam.

sorry i have not so much time for cammill at the moment :(

**Comment by blacksheep1970** [comment]
Let me know if I can help. I am not a coder but good in organization :) What about creating a website with a forum and make some advertisement (e.g. at linuxcnc.org) to get more coders involved?
I would really like to help pushing this awesome piece of software forward.

Regards
Michael

**Comment by mcules** [comment]
A Website will be a good thing.

**Comment by adbensi** [comment]
can count with me as a programmer, I loved cammil
I have a modified version for myself use, tomorrow I will update my github
with this..
Em 27/01/2015 16:11, "Dennis Eisold" <notifications@github.com> escreveu:

**Comment by adbensi** [comment]
Hi, I have new pocket file on the github,
now I can do pocket by step... :)
https://github.com/adbensi/cammill/compare/multigcs:master...master

**Comment by multigcs** [comment]
hi adbensi ,
please setup your editor to use unix fileformat, because it makes git and diff unusable and i can not add you pull-requests.

**Comment by adbensi** [comment]
I noticed this today ... thanks. It is possible to compare with the diff -b
I will fix it, thanks again :)
Best regards
Em 09/02/2015 19:54, "multigcs" <notifications@github.com> escreveu:

**Comment by blacksheep1970** [comment]
Ok, so I will work on a website with a forum for the project and host it on my server. Do we need mailing lists for dev and or users?

**Comment by adbensi** [comment]
My opinion: I think not
But post forum yes..

Very nice idea!
I can moderate too
Em 26/02/2015 08:57, "blacksheep1970" <notifications@github.com> escreveu:

**Comment by sliptonic** [comment]
Hey guys.  I'm glad to see some interest in keeping this project alive.  There are a lot of stale and dead CAM projects littering the landscape and a serious need for some better tools.

I noticed some weirdness in the license headers of some of the files like this:
https://github.com/multigcs/cammill/blob/master/pocket.c

It appears to be GPL 3 but paragraph 4 refers to GPL 2+  Is that correct?

GPL2+ might make this code really interesting to a number of different FOSS CAD/CAM projects but GPL3 is, unfortunately, incompatible. 

Anyway, I just thought I'd mention it.  
Cheers.

**Comment by blacksheep1970** [comment]
I have ordered the domain cammill.org and reserved the space on my webserver. I will install at upcoming weekend the CMS Drupal with some additional Modules (Community related, Forum). 
I will install some free template themes and we can consider then which one we use for the project.

Regards,
Michael

**Comment by blacksheep1970** [comment]
Update: Still waiting for registration confirmation of the domain cammill.org.

**Comment by blacksheep1970** [comment]
Update: Due to sickness I was delayed. Site is meanwhile online and I am playing around with the design and implemented the Forum. Need some further days, but I will enable user registration now. Feel free to register

**Comment by adbensi** [comment]
I am estimate improvements for you.

The forum is very beautiful,
very good appearance,
congratulations!

With the domain and forum will be easier to publish and find the project :)
I put it on the hardkernel :)
Em 12/03/2015 05:28, "blacksheep1970" <notifications@github.com> escreveu:

**Comment by koppi** [comment]
@blacksheep1970 is cammill.org down?

**Comment by adbensi** [comment]
Here's alive.
Em 18/05/2015 17:21, "Jakob Flierl" <notifications@github.com> escreveu:

**Comment by koppi** [comment]
I just created the org https://github.com/cammill – hope you all will join the invitation and push things forward.

**Comment by multigcs** [comment]
complete moved to https://github.com/cammill/cammill
