### ISSUE TITLE
Segmentation error

### ISSUE THREAD

**Issue by deusyss** [multigcs/cammill#7]
Hi,

I use Librecad to draw my dxf. When i insert text in my dxf, save it, and try to open in cammill, it closed without message except segmentation fault. Could be well to try/catch error on opening files.

Solutions to have no problem (and the right solution to engrave correctly): explode text

**Comment by multigcs** [comment]
sorry, my librecad is broken at the moment, so i can not add text in the drawing, please upload a test-file

**Comment by adbensi** [comment]
You need one standard iso dxf ASCII file compatible with cad12, try
draftsight, then you know how setup librecad lately
Em 09/02/2015 18:40, "deusyss" <notifications@github.com> escreveu:

**Comment by deusyss** [comment]
Thanks for the feedback. I never pay attention to the dxf type. I'll do now.
