### ISSUE TITLE
Postprocessor

### ISSUE THREAD

**Issue by deusyss** [multigcs/cammill#8]
In some case, generated G-code have error.
Example: "G02 I-nan J-nan".

**Comment by adbensi** [comment]
There are details in Your design are preventing the compensation of the
tool.
if your tool has 2mm in diameter, round every corner with a radius of 1.05
Em 09/02/2015 18:45, "deusyss" <notifications@github.com> escreveu:

**Comment by deusyss** [comment]
Hi,
Does that mean that i have to anticipate the tool to use? in my mind, it is to the software to correct GCODE no?

**Comment by adbensi** [comment]
No. and yes :)
see, if you draw a hole 2mm and set a 2mm tool, you will need to reduce the
tool or enlarge the hole to 2.05.
The same thing happens with sharp corners, you need to round up as the tool
diameter
http://www.smithy.com/cnc-reference-info/chapter-9/tool-compensation-detail/page/4
Em 10/02/2015 04:57, "deusyss" <notifications@github.com> escreveu:

**Comment by deusyss** [comment]
OK, thanks for the explanation.  Now how to do to never have more this problem ("i-nan j-nan")?

**Comment by adbensi** [comment]
Adjusting the design to cammill can make compensation
Please attach the file

A4.5: Chanfros e arredondamentos - Curso Gratuito…:
http://youtu.be/Cm2XMI2LqGo
 Em 10/02/2015 15:44, "deusyss" <notifications@github.com> escreveu:

**Comment by deusyss** [comment]
Hi, please find the generated file. the JPG is the dxf and the png the ngc. With a new version of Cammill (Default values), the error appears again.
![test](https://cloud.githubusercontent.com/assets/5519444/6152980/72a5ecf0-b221-11e4-955e-362a4d2e7023.jpg)
![test2](https://cloud.githubusercontent.com/assets/5519444/6153000/920efa8c-b221-11e4-9976-29fbacfc427c.png)

**Comment by adbensi** [comment]
I can not see the attachments, but is not an error.
Laser mode works fine with your drawing, but cutter needs some
consideration:

hole larger than the tool and corners with a radius greater than 1/2 of the
tool diameter.
Em 11/02/2015 16:11, "deusyss" <notifications@github.com> escreveu:

**Comment by deusyss** [comment]
OK. Thanks for your answer. Could i suggest, as new feature, that Cammill manage itself this modification? We don't always know by advance which tool we are going to use; a tool correction by Cammill would be a very great feature.

**Comment by deusyss** [comment]
Just a fast message to make a feedback for other user.
As Adbsensi said, if you see "I-nan" and or "J-nan" in your GCODE, you ve to modify the dxf or change your tool (a smaller diameter). But there is a hiden problem so.
In fact, when "*-nan" is generated, it crashes the GCODE generation for the object. If you just delete these problem lines, as i try, the physical traduction i saw is that the spindle start to go down but it doesn't stop and go ahead through material.
If you have this "-nan" problem, try to use "free tool" and reduce the diameter mm by mm (or inch by inch). You could see so that when the "-nan" problem disappear, several lines appears for the concerned object.
A try catch could be code in the GCODE generation, and if "-nan" problem is detected, a error message could be display.
